# -*- coding: utf-8 -*-
"""Bulk_Cheque_Rename.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_nu0KFWXJCmZWJ3IWFTu3n4A64iE_Crh

This file helps to correct the names of the annotated images and labels obtained from Roboflow
"""

import os

# Directory containing the files - one for images and other for labels
directory = 'train\images'

# Sample Image - Cheque091_jpg.rf.816ae9905524e7d20ebca21c1f3df518.jpg
# Loop through each file in the directory
for filename in os.listdir(directory):

    if "_jpg.rf." in filename:
        # Extract the new filename by splitting at '_jpg.rf.' and adding '.jpg'
        new_filename = filename.split("_jpg.rf.")[0] + ".jpg"

        # Rename the file
        old_filepath = os.path.join(directory, filename)
        new_filepath = os.path.join(directory, new_filename)
        os.rename(old_filepath, new_filepath)

print("Images renamed successfully!")


directory = 'train\labels'

# Sample Label - Cheque091_jpg.rf.816ae9905524e7d20ebca21c1f3df518.txt
# Loop through each file in the directory
for filename in os.listdir(directory):

    if "_jpg.rf." in filename:
        # Extract the new filename by splitting at '_jpg.rf.' and adding '.txt'
        new_filename = filename.split("_jpg.rf.")[0] + ".txt"

        # Rename the file
        old_filepath = os.path.join(directory, filename)
        new_filepath = os.path.join(directory, new_filename)
        os.rename(old_filepath, new_filepath)

print("Labels renamed successfully!")